if(NOT DEFINED FBX_ROOT)
    if(APPLE)
        set(FBX_EXT_DIR "/Applications/Autodesk/FBX SDK/2020.3.7/")
    elseif(UNIX)
        set(FBX_EXT_DIR "${PROJECT_SOURCE_DIR}/external/fbxsdk/")
    endif()
    if(MSVC)
        message(WARNING "WINDOWS IS CURRENTLY NOT SUPPORTED.")
    endif()
else()
    set(FBX_EXT_DIR ${FBX_ROOT})
endif()

if (APPLE)
    find_file(FBX_LIBRARY libfbxsdk.a "${FBX_EXT_DIR}lib/clang/release/")
elseif(UNIX)
    find_file(FBX_LIBRARY libfbxsdk.a "${FBX_EXT_DIR}lib/")
elseif(WIN32)
    message(FATAL_ERROR "Windows is not supported.")
else()
    message(FATAL_ERROR "Unknown OS for FBX loader.")
endif()


#find_file(FBX_LIBRARY libfbxsdk.a ${PROJECT_SOURCE_DIR}/external/fbxsdk/lib/)
find_file(FBX_INCLUDE fbxsdk.h "${FBX_EXT_DIR}/include/")

if (NOT FBX_LIBRARY OR NOT FBX_INCLUDE)
    set(FBX_FOUND 0)
    unset(FBX_LIB)
    unset(FBX_INCLUDE)
    message(WARNING "FBXSDK NOT found in ${FBX_EXT_DIR}. Please make sure to install FBX SDK and set the FBX_ROOT variable.")
else()
    find_package(LibXml2 REQUIRED)
    find_package(ZLIB REQUIRED)
    set(FBX_FOUND 1)
    set(FBX_INCLUDE_DIRS "${FBX_EXT_DIR}/include/")
    set(FBX_LIBRARIES ${FBX_LIBRARY} ${LIBXML2_LIBRARIES} ${ZLIB_LIBRARIES})

    if (APPLE)
        find_package(Iconv MODULE REQUIRED)
        set(CARBON_LIBRARIES /System/Library/Frameworks/Carbon.framework)
        set(FBX_LIBRARIES ${FBX_LIBRARIES} ${Iconv_LIBRARIES} ${CARBON_LIBRARIES})
    endif ()

    add_definitions(-DHAVE_FBX)
endif()

